export const errors = {
	userNotFound: 'userNotFound',
	invalidPassword: 'invalidPassword',
	invalidEmail: 'invalidEmail',
	invalidUsername: 'invalidUsername',
	invalidPhoneNumber : 'invalidPhoneNumber',
	passwordTooWeak: 'passwordTooWeak',
	wrongParameters: 'wrongParameters',
	unauthorized: 'unauthorized',
	expired: 'expired',
	unprivileged: 'unprivileged',
	serverError: 'serverError',
	emailTaken: 'emailTaken',
	mobileTaken: 'mobileTaken',
	usernameTaken: 'usernameTaken',
	tokenNotFound: 'emailTokenNotFound',
	tokenExpired: 'emailTokenExpired',
	notFound: 'notFound',
	invalidComplaintID : 'invalidComplaint',
	invalidPlanID : 'invalidPlanID',
	productExist : 'productExist',
	productNotExist : 'productNotExist',
	complaintNotFound: 'complaintNotFound',
	productNotFound: 'productNotFound'
};

export const messages: { [index: string]: string } = {
	userNotFound: 'The document you are looking for is either deleted or has been moved. Please check your link again',
	invalidPassword: 'Your password seems to be incorrect',
	invalidEmail: 'Your email address is not valid',
	invalidUsername: 'Your username is not valid',
	invalidPhoneNumber : 'Your phone number is not valid',
	passwordTooWeak: 'Your password is too weak. Please choose a stronger password',
	wrongParameters: 'An internal error occured. This incident has been reported',
	unauthorized: 'An error occured. If this persists, please contact the administrator',
	expired: 'An error occured. If this persists, please try logging in again',
	unprivileged: 'You do not have the permission to perform that action',
	serverError: 'An internal server error has occured. Please try again later',
	emailTaken: 'Sorry. That email address is already in use.',
	mobileTaken: 'Sorry. That mobile number is already in use.',
	usernameTaken: 'Sorry. That username is taken.',
	tokenNotFound: 'Your link seems to be invalid. Please request for a new link again',
	tokenExpired: 'Your link has expired. Please request for a new link again',
	notFound: 'That route doesn\'t seem to exist',
	invalidComplaintID: 'no complaints found for the given ID',
	invalidPlanID : 'no plans found for the given ID',
	productExist: 'product with that name already exists',
	productNotExist: 'product with that name does not already exists',
	complaintNotFound : 'The complaint you are trying to find does not exist.',
	productNotFound : 'The product you are trying to find does not exist.'
};
